import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
     <div>
        <Head>
          <title>Dark+Light Mode Template</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="../Images/favicon.ico" />
        </Head>
        
          <main className={styles.main}>
            <h1> (Next.js + MaterialUI) dark + light mode Template </h1>
          </main>

        <footer className={styles.footer}>
          © 2022 Your Name
        </footer>
     </div>
   
  )
}